### PR TITLE
Upstream update: remove `external` dependency dir

### PR DESCRIPTION
**Pull request by rheinwein**
Don't use the external directory for dependencies. Reference the package by name only, and let go/godep do the work.

This is a cherry-picked commit from upstream, as well as renaming all of the dependencies from (for example) `github.com/fsouza/go-dockerclient/external/github.com/docker/docker/package` to simply `github.com/docker/docker/package`.

I also set up testing with Jet.

### CODE REVIEW

**Comment by beanieboi** [comment]
😍

**Comment by krames** [comment]
Awesome!!! :+1: This going to make jet development fun again!!!

**Comment by bfosberry** [comment]
:+1: do eeet

**Comment by beanieboi** [comment]
hell yeah!

**Pull request merged**
